# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('src/ui/components', 'src/ui/components'),
        ('src/ui', 'src/ui'),
        ('src/simulador', 'src/simulador'),
        ('data', 'data'),
    ],
    hiddenimports=[
        'src.ui.main_window',
        'src.ui.components.file_loader',
        'src.ui.components.policy_selector',
        'src.ui.components.parameter_input',
        'src.ui.components.results_tab',
        'src.ui.components.stats_tab',
        'src.simulador.simulador',
        'src.simulador.exportador_pdf',
        'src.simulador.proceso',
        'src.simulador.algoritmos.FCFS',
        'src.simulador.algoritmos.PE',
        'src.simulador.algoritmos.RR',
        'src.simulador.algoritmos.SPN',
        'src.simulador.algoritmos.SRTN',
        'customtkinter',
        'matplotlib',
        'numpy',
        'screeninfo',
        'reportlab',
        'reportlab.pdfgen',
        'reportlab.lib',
        'reportlab.lib.pagesizes',
        'reportlab.lib.styles',
        'reportlab.lib.colors',
        'reportlab.platypus',
        'reportlab.platypus.tables',
        'reportlab.platypus.paragraph',
        'reportlab.platypus.frames',
        'reportlab.platypus.doctemplate',
        'reportlab.lib.enums',
        'reportlab.graphics',
        'reportlab.graphics.shapes',
        'reportlab.graphics.charts',
        'reportlab.graphics.charts.barcharts',
        'reportlab.graphics.charts.piecharts',
        'reportlab.lib.units',
        'tkinter',
        'tkinter.filedialog',
        'tkinter.messagebox',
        'json',
        'os',
        'datetime',
        'subprocess',
        'platform',
        'sys',
        'copy',
        'math',
        'collections',
        'webbrowser',
        'shutil',
        'tempfile',
        'time',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='Simulador_Planificacion',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='docs/imagenes/icon.ico',
)
